language: python
os: linux

python:
  - 3.9

jobs:
  - name: test    
    install:
      - cd ebdj && pip install -r requirements.txt

    before_script:
      - cd ebdj
      - python manage.py migrate
      - python manage.py collectstatic --noinput

    script:
      - cd ebdj
      - black --check .
      - flake8 .
      - coverage run --source=polls manage.py test

    after_script:
      - cd ebdj && coveralls

    deploy:
      provider: elasticbeanstalk
      access_key_id:
        secure: AWS_ACCESS_KEY_ID
      secret_access_key:
        secure: AWS_ACCESS_SECRET_KEY
      region: "us-east-1"
      app: "ebdj2"
      env: "env-ebdj-dev"
      bucket_name: "elasticbeanstalk-us-east-1-994011800090"
      on:
        all_branches: true
